---

name: CI macOS

# NB: (2023-04-29) This workflow is SUSPENDED because we need a
# gnat_external compiler with langkit, libadalang, libgmp included,
# and we can't provide that on Github.

on:
  push:
  pull_request:

jobs:
  build:
    name: CI on macOS

    runs-on: macos-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: alire-project/setup-alire
      uses: alire-project/setup-alire@v1
    -
      name: Install toolchain
      run: |
        alr --non-interactive config --global --set toolchain.assistant false
        alr --non-interactive toolchain --install gnat_native
        alr --non-interactive toolchain --install gprbuild
        alr --non-interactive toolchain --select gnat_native
        alr --non-interactive toolchain --select gprbuild
    # -
    #   No need to set up Homebrew, it has gmp already included.
    -
      name: Build and run
      run: |
        eval $(brew shellenv)
        alr --non-interactive build
